"""Generate a VMD visualization script (`.vmd`) for a built LD system.

Writes a self-contained Tcl script that loads the structure (and optional
trajectory) and sets one representation per component -- neutral-lipid core,
cholesteryl ester, each phospholipid, phosphates, water and ions -- colored so
the trilayer / leaflet structure reads at a glance.  Run it with::

    vmd -e view.vmd

Only components actually present in the structure get a representation.
"""

import os

import MDAnalysis as mda

# (resname-or-name selection, VMD style, VMD ColorID, human label)
# ColorIDs: 0 blue, 1 red, 3 orange, 6 silver, 7 green, 8 white, 10 cyan, 11 purple
_REPS = [
    ("resname TRIO",            "Licorice 0.3 12.0", 3,  "TRIO core (orange)"),
    ("resname CHYO",            "Licorice 0.3 12.0", 11, "CHYO cholesteryl ester (purple)"),
    ("resname POPC",            "Lines 2.0",         0,  "POPC (blue)"),
    ("resname DOPE",            "Lines 2.0",         7,  "DOPE (green)"),
    ("resname SAPI",            "Lines 2.0",         10, "SAPI (cyan)"),
    ("resname POPE POPG POPS PSM CHL1", "Lines 2.0", 4,  "other lipids (yellow)"),
    ("name P",                  "VDW 1.0 16.0",      6,  "phosphates (silver)"),
    ("resname SOD CLA POT",     "VDW 0.5 12.0",      1,  "ions (red)"),
    ("resname TIP3 SOL",        "Points 1.0",        8,  "water (white)"),
]


def _present_selections(universe):
    """Yield (selection, style, colorid, label) reps that match >=1 atom."""
    for sel, style, cid, label in _REPS:
        if len(universe.select_atoms(sel)):
            yield sel, style, cid, label


def write_vmd(structure, path, trajectory=None, wrap=True):
    """Write a VMD `.vmd` script for ``structure`` (a .gro path or Universe).

    Parameters
    ----------
    structure : str or mda.Universe
        The system to visualize.  If a Universe is passed you must also pass a
        real ``structure_path`` via ``trajectory``-style loading -- normally give
        a file path so the script can reload it.
    path : str
        Output ``.vmd`` path.
    trajectory : str or None
        Optional trajectory (.xtc/.trr/.dcd) to append for animation.
    wrap : bool
        Emit PBCTools commands to draw the box and wrap molecules whole.
    """
    if isinstance(structure, mda.Universe):
        struct_path = getattr(structure, "filename", None)
        if not struct_path:
            raise ValueError("pass a file path (not an in-memory Universe) as structure")
        struct_path = str(struct_path)
        u = structure
    else:
        struct_path = structure
        u = mda.Universe(structure)

    struct_ftype = os.path.splitext(struct_path)[1].lstrip(".") or "gro"
    lines = [
        "# VMD visualization generated by ld_maker",
        "# run with:  vmd -e " + os.path.basename(path),
        "",
        "mol delete all",
        f'mol new "{struct_path}" type {{{struct_ftype}}} waitfor all',
    ]
    if trajectory:
        traj_ftype = os.path.splitext(trajectory)[1].lstrip(".") or "xtc"
        lines.append(f'mol addfile "{trajectory}" type {{{traj_ftype}}} waitfor all')
    lines += ["mol delrep 0 top", ""]

    for sel, style, cid, label in _present_selections(u):
        lines += [
            f"# {label}",
            f"mol representation {style}",
            f"mol color ColorID {cid}",
            "mol material Opaque",
            f"mol selection {{{sel}}}",
            "mol addrep top",
            "",
        ]

    lines += ["display projection Orthographic", "display resetview", "axes location Off"]
    if wrap:
        lines += [
            "# requires the PBCTools plugin (bundled with VMD)",
            "if {![catch {package require pbctools}]} {",
            "  catch {pbc box}",
            "  catch {pbc wrap -compound res -center com -all}",
            "}",
        ]
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    return path


if __name__ == "__main__":
    import argparse
    p = argparse.ArgumentParser(prog="ld_maker.vmd",
                                description="Write a VMD .vmd script for a built LD system.")
    p.add_argument("structure", help="system .gro/.pdb")
    p.add_argument("-o", "--out", default=None, help="output .vmd (default: <structure>.vmd)")
    p.add_argument("-t", "--trajectory", default=None, help="optional trajectory to animate")
    args = p.parse_args()
    out = args.out or os.path.splitext(args.structure)[0] + ".vmd"
    write_vmd(args.structure, out, trajectory=args.trajectory)
    print(f"wrote {out}  (vmd -e {out})")
